In [1]:
print('Hello I am excited to learn PyTorch')

Hello I am excited to learn PyTorch


**Introduction to Tensors** <br>
PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [2]:
import torch
torch.__version__

'2.0.1+cu118'

In [3]:
# scalar - 0 dim tensors
scalar = torch.tensor(7)
print(scalar, scalar.ndim) # .ndim outputs the dimension of the tensor
print(scalar.item()) # converts tensor to regular python int

tensor(7) 0
7


In [4]:
# vector - 1 dim tensors
vector = torch.tensor([4, 5])
print(vector, vector.ndim)
print(vector.shape) # 2x1 vector

tensor([4, 5]) 1
torch.Size([2])


In [5]:
# matrix - 2 dim tensors
mat = torch.tensor([[4, 5],
                    [4, 3]])
print(mat, mat.ndim)
print(mat.shape) # 2x2 matrix

tensor([[4, 5],
        [4, 3]]) 2
torch.Size([2, 2])


![picture](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

In [6]:
# tensor - n dim
tens = torch.tensor([[[4, 3, 4],
                      [4, 2, 1],
                      [9, 0, 7]]])
print(tens, tens.ndim)
print(tens.shape)

tensor([[[4, 3, 4],
         [4, 2, 1],
         [9, 0, 7]]]) 3
torch.Size([1, 3, 3])
