# TORCH BASICS

### reshaping, stacking, squeezing, and unsqueezing tensors

- **reshaping:** reshapes an input tensro to a defined shpae
- **view:** return a view of an input tensor of certain shape but keep the same memory as the original tensor
- **stacking:** combine multiple tensors on top of each other (vstack) or side by side (hstack)
- **squeeze:** removes all `1` dimensions from a tensor
- **unsqueeze:** add a `1` dimesion to a target tensor
- **permute:** return a view of the input with dimensions swapped in a certain way

In [1]:
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [2]:
# add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [3]:
# change the view
z = x.view(1, 9)
print(z, z.shape)

# nb: chaing z changes z because a view of tensor shares the same memory
z[:,4] = 999
print(
    f'z: {z} \nx: {x}'
)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
z: tensor([[  1.,   2.,   3.,   4., 999.,   6.,   7.,   8.,   9.]]) 
x: tensor([  1.,   2.,   3.,   4., 999.,   6.,   7.,   8.,   9.])


In [4]:
# stack tensors on top of each other (dim=0)
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

tensor([[  1.,   2.,   3.,   4., 999.,   6.,   7.,   8.,   9.],
        [  1.,   2.,   3.,   4., 999.,   6.,   7.,   8.,   9.],
        [  1.,   2.,   3.,   4., 999.,   6.,   7.,   8.,   9.]])

In [5]:
# removing single dimension from a tensor
y = x.view(9,1) # adding a dimension of 1 to the tensor

y_squeezed = y.squeeze()
y.shape, y_squeezed.shape

(torch.Size([9, 1]), torch.Size([9]))

In [6]:
# adding single dimension to a tensor
print(
    f'z original: {z} \nz original shape: {z.shape}'
)
print(
    f'z unsqueezed: {z.unsqueeze(-1)} \nz unsqueezed shape: {z.unsqueeze(-1).shape}'
)

z original: tensor([[  1.,   2.,   3.,   4., 999.,   6.,   7.,   8.,   9.]]) 
z original shape: torch.Size([1, 9])
z unsqueezed: tensor([[[  1.],
         [  2.],
         [  3.],
         [  4.],
         [999.],
         [  6.],
         [  7.],
         [  8.],
         [  9.]]]) 
z unsqueezed shape: torch.Size([1, 9, 1])


In [7]:
# rearranging the dimensions of a tensor
w = z.unsqueeze(-1)
print(w.shape)

w_permuted = w.permute(0, 2, 1) # swapped dim=1 with dim=2
print(w_permuted.shape)

# nb: this function also creates a view of the original tensor (i.e change w, changes w_permuted)
w[0, 2, 0] = -100
w, w_permuted

torch.Size([1, 9, 1])
torch.Size([1, 1, 9])


(tensor([[[   1.],
          [   2.],
          [-100.],
          [   4.],
          [ 999.],
          [   6.],
          [   7.],
          [   8.],
          [   9.]]]),
 tensor([[[   1.,    2., -100.,    4.,  999.,    6.,    7.,    8.,    9.]]]))

In [8]:
w, w.dim()

(tensor([[[   1.],
          [   2.],
          [-100.],
          [   4.],
          [ 999.],
          [   6.],
          [   7.],
          [   8.],
          [   9.]]]),
 3)

In [9]:
w_permuted.dim()

3

In [10]:
x = torch.arange(1, 10).reshape(1,3,3)

In [11]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
x[0,2,2]#.item()

tensor(9)

In [13]:
x[0,:,2]

tensor([3, 6, 9])

### pytorch tensors & numpy

- `torch.from_numpy(ndarray)`: numpy array to tensor
- `torch.Tenor.numpy()`: from torch tensor to numpy

In [14]:
import torch
import numpy as np

In [15]:
# from numpy to tensor
array = np.arange(1, 10)
tensor = torch.from_numpy(array)

array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [16]:
# from tensor to numpy
tensor2 = torch.arange(20, 30)
array2 = tensor2.numpy()

array2, tensor2

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 tensor([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))

### reproducibililt in pytorch

(trying to take random out of random using a random seed)

in short how a neural network learns: 

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`

In [17]:
random_tensor_a = torch.rand(3, 4) # produces random values every time this cell runs
random_tensor_b = torch.rand(3, 4)

random_tensor_a == random_tensor_b
# it is rare to get smae values in both tensors

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
import torch 

# set random seed 
torch.manual_seed(97)
random_tensor_c = torch.rand(3, 4)
torch.manual_seed(97)
random_tensor_d = torch.rand(3, 4)

random_tensor_c == random_tensor_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [19]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [20]:
print(device)

cpu
